### ISSUE TITLE
fail debuild at mrbtest

### ISSUE THREAD

**Issue by murasesyuka** [mruby-debian/mruby#1]
debuild not define $SHELL environment variable.

same matter : https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/5YqPIYbZxhY

``` sh
$ gbp buildpackage --git-ignore-new --git-upstream-tree="upstream/1.1.0+20151021+git68ba3862" --git-builder="debuild -i -us -uc -b"
.
..
...
..
.
Kernel#Hash : .

Skip: Module#prepend super in alias  super does not currently work in aliased methods
Total: 881
   OK: 881
   KO: 0
Crash: 0
 Time: 0.07 seconds

ruby test/bintest.rb "/home/murase/git/debian-mruby/mrbgems/mruby-compiler" "/home/murase/git/debian-mruby/mrbgems/mruby-bin-mirb" "/home/murase/git/debian-mruby/mrbgems/mruby-bin-mruby" "/home/murase/git/debian-mruby/mrbgems/mruby-bin-strip"
F..Fsh: 1: binmrbc.exe: not found
sh: 1: binmruby.exe: not found
Fsh: 1: binmruby.exe: not found
sh: 1: binmrbc.exe: not found
sh: 1: binmruby.exe: not found
sh: 1: binmruby.exe: not found
Fsh: 1: binmruby.exe: not found
FFFFsh: 1: binmrbc.exe: not found
sh: 1: binmrbc.exe: not found
sh: 1: binmruby-strip.exe: not found
sh: 1: binmruby.exe: not found
sh: 1: binmruby.exe: not found
sh: 1: binmruby-strip.exe: not found
Fsh: 1: binmrbc.exe: not found
sh: 1: binmrbc.exe: not found
sh: 1: binmruby-strip.exe: not found
.sh: 1: binmrbc.exe: not found
sh: 1: binmrbc.exe: not found
sh: 1: binmruby-strip.exe: not found
sh: 1: binmruby.exe: not found
sh: 1: binmruby.exe: not found
/home/murase/git/debian-mruby/test/report.rb:3:in `<top (required)>': mrbtest failed (KO:10, Crash:0) (RuntimeError)
    from test/bintest.rb:18:in `load'
    from test/bintest.rb:18:in `<main>'
F
Fail: Compiling multiple files without new line in last line. #2361
 - Assertion[1] Failed: Expected to be equal
    Expected: "bin\\mrbc.exe:/tmp/a.rb20151109-13050-6q14kw:Syntax OK"
      Actual: "sh: 1: binmrbc.exe: not found"
 - Assertion[2] Failed: Expected to be equal
    Expected: 0
      Actual: 127
Fail: regression for #1564
 - Assertion[1] Failed: Expected to be equal
    Expected: "sh: 1: binmruby.exe: not found\n"
      Actual: "-e:1:2: syntax error, unexpected tLSHFT\n"
 - Assertion[2] Failed: Expected to be equal
    Expected: "sh: 1: binmruby.exe: not found\n"
      Actual: "-e:1:3: syntax error, unexpected tLSHFT\n"
Fail: regression for #1572
 - Assertion[1] Failed: Expected to be equal
    Expected: ""
      Actual: "\"ok\""
Fail: $0 value
 - Assertion[1] Failed: Expected to be equal
    Expected: "\"/tmp/test.rb20151109-13050-1okx4o7\""
      Actual: ""
 - Assertion[2] Failed: Expected to be equal
    Expected: "\"/tmp/test.mrb20151109-13050-14sptrp\""
      Actual: ""
 - Assertion[3] Failed: Expected to be equal
    Expected: "\"-e\""
      Actual: ""
Fail: __END__ [8.6]
 - Assertion[1] Failed: Expected to be equal
    Expected: "\"test\"\n\"fin\"\n"
      Actual: ""
Fail: no files
 - Assertion[1] Failed: Expected to be equal
    Expected: 1
      Actual: 127
 - Assertion[2] Failed: Expected to be equal
    Expected: "no files to strip"
      Actual: "sh: 1: binmruby-strip.exe: not found"
Fail: file not found
 - Assertion[1] Failed: Expected to be equal
    Expected: 1
      Actual: 127
 - Assertion[2] Failed: Expected to be equal
    Expected: "can't open file for reading not_found.mrb\n"
      Actual: "sh: 1: binmruby-strip.exe: not found\n"
Fail: not irep file
 - Assertion[1] Failed: Expected to be equal
    Expected: 1
      Actual: 127
 - Assertion[2] Failed: Expected to be equal
    Expected: "can't read irep file /tmp/script.rb20151109-13050-10e71z5\n"
      Actual: "sh: 1: binmruby-strip.exe: not found\n"
Fail: success
 - Assertion[1] Failed: Expected to be equal
    Expected: 0
      Actual: 127
 - Assertion[4] Failed: Expected to be equal
    Expected: 0
      Actual: 127
Fail: check lv section
 - Assertion[1] Failed: Expected false to be true
    Expected: true
      Actual: false
 - Assertion[2] Failed: Expected to be equal
    Expected: "[:a, :b]"
      Actual: ""
 - Assertion[3] Failed: Expected to be equal
    Expected: "[]"
      Actual: ""
Total: 13
   OK: 3
   KO: 10
Crash: 0
 Time: 0.09 seconds
rake aborted!
Command Failed: [ruby test/bintest.rb "/home/murase/git/debian-mruby/mrbgems/mruby-compiler" "/home/murase/git/debian-mruby/mrbgems/mruby-bin-mirb" "/home/murase/git/debian-mruby/mrbgems/mruby-bin-mruby" "/home/murase/git/debian-mruby/mrbgems/mruby-bin-strip"]
Rakefile:119:in `block (2 levels) in <top (required)>'
Makefile:12: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/murase/git/debian-mruby'
dh_auto_test: make -j1 test returned exit code 2
debian/rules:4: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1374:
dpkg-buildpackage -rfakeroot -D -us -uc -i -b failed
gbp:error: 'debuild -i -us -uc -b' failed: it exited with 29

```

**Comment by murasesyuka** [comment]
make patch and success debuild.

patch : https://github.com/mruby-debian/mruby/commit/5ded4d4f95ed6ede7dafe49a347d2edd8c35ff31
